services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminbpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - skipper-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d main"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=main
      - DB_USERNAME=admin
      - DB_PASSWORD=adminbpassword
    networks:
      - skipper-network

volumes:
  pgdata:
networks:
  skipper-network:
    driver: bridge