services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - DB_HOST=79.174.88.214
      - DB_PORT=16685
      - DB_DATABASE=db1
      - DB_USERNAME=user1
      - DB_PASSWORD=beQzojU$#1re0FZ2o70ijJ5w
    networks:
      - skipper-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - skipper-network
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - skipper-network

volumes:
  pgdata:
networks:
  skipper-network:
    driver: bridge
