services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - DB_HOST=79.174.88.19
      - DB_PORT=19582
      - DB_DATABASE=db1
      - DB_USERNAME=admin
      - DB_PASSWORD=Grove312666
    networks:
      - skipper-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`yoho-webapp.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=3000" # Adjust if your app listens on a different port

  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true" # Remove or secure in production
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=gevernus@mail.ru"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/letsencrypt:/letsencrypt"
    networks:
      - skipper-network
    restart: always

networks:
  skipper-network:
    driver: bridge

volumes:
  pgdata:
  traefik: