services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminbpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - skipper-network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d main" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=main
      - DB_USERNAME=admin
      - DB_PASSWORD=adminbpassword
    networks:
      - skipper-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - skipper-network
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'"
    networks:
      - skipper-network

volumes:
  pgdata:
networks:
  skipper-network:
    driver: bridge
